let dataArr = [
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending1.jpg",
    category: "Men",
    title: "Cashmere Tank + Bag",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending2.jpg",
    title: "Cashmere Tank + Bag",
    category: "Women",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending3.jpg",
    title: "Cashmere Tank + Bag",
    category: "Baby",
    price: "$98.00",
    oldPrice: "$120.00",
  },
  {
    img: "./assets/images/indexPage/trending4.jpg",
    title: "Cashmere Tank + Bag",
    category: "Fashion",
    price: "$98.00",
    oldPrice: "$120.00",
  },
];
